# TGIF

Note from **Image-Caption-Generator-App** - https://github.com/AIAnytime/Image-Caption-Generator-App

много ноутов с примерами загрузги других video_capting datasets - https://github.com/jssprz/video_captioning_datasets/tree/main/preprocess_corpus

Датасет отсюда - https://github.com/raingo/TGIF-Release/tree/master

HF тоже TGIF - https://huggingface.co/datasets/HuggingFaceM4/TGIF/tree/main

# Load dataset

In [ ]:
!git clone https://github.com/raingo/TGIF-Release.git -q

fatal: destination path 'TGIF-Release' already exists and is not an empty directory.


In [ ]:
import os
import pandas as pd

gif_df = pd.read_csv('/content/TGIF-Release/data/tgif-v1.0.tsv', sep='\t', header=None)


In [ ]:
gif_df.sample(10)

0  \
123338  https://33.media.tumblr.com/5e4a22ac259dea7842...   
72363   https://31.media.tumblr.com/79b82868b907c05a46...   
120504  https://38.media.tumblr.com/94a3da226c0662d773...   
14583   https://33.media.tumblr.com/679f302d91c8884d8c...   
117127  https://33.media.tumblr.com/411193b2f4c8cabaca...   
73781   https://33.media.tumblr.com/5bcf207992d97aa8e5...   
77106   https://38.media.tumblr.com/3e3037c0145a56e05b...   
53967   https://31.media.tumblr.com/20ae3ae50bd6f65978...   
9606    https://38.media.tumblr.com/164c23a485e253d965...   
115946  https://33.media.tumblr.com/892ebd1b078055a0fd...   

                                                        1  
123338  a man is walking around singing with a car beh...  
72363   a man is outside singing and playing an air gu...  
120504              a fat man is giving kiss and smiling.  
14583   a man wearing a red reindeer hat in the street...  
117127  a girl is dancing from side to side while the ...  
73781   Three young boys are making motions with their...  
77106                    four men in a group are dancing.  
53967       two guys are jumping around for joy in a room  
9606    glitter is being thrown at a man in a white sh...  
115946      three guys are dancing and singing in a room.

In [ ]:
gif_df.shape

(125782, 2)

## Random view

In [ ]:
from IPython.display import Image
gif_idx = gif_df.sample().index[0] #rand id

caption_original = gif_df[1][gif_idx]
print(f'caption_original of {gif_idx} gif: {caption_original}\n')
url = gif_df[0][gif_idx]
print(f'url = {url}\n')
Image(url=url)  # external

caption_original of 122876 gif: a young man wearing violet is talking.

url = https://33.media.tumblr.com/96d4eb56bd7a4ea6d09d208cd4619d3e/tumblr_nf63x9XNF61s7be03o1_250.gif



# Install libs


# Prepare dataset



## Seach videos with specific captions (for examples in papers and presentations only)

In [ ]:
import random
with open('/content/TGIF-Release/data/splits/train.txt') as f:
    train_vids = [l.strip() for l in f.readlines()]  # urls
    train_df = gif_df[gif_df[0].isin(train_vids)]
    train_vidxs, train_corpus = list(train_df.index.values), list(train_df[1])

In [ ]:
patterns_to_search = ["microphone",  "dance"] # , "sing"

matchs = [(train_vidxs[i], s) for (i, s) in enumerate(train_corpus) if all([(p in s) for p in patterns_to_search])]
print(len(matchs))
matchs

61


[(1562, "a man sing's and dances in front of a microphone"),
 (2337, 'a woman dances around while is holding a microphone.'),
 (5646, 'a woman dances and whip her hair in front of a microphone.'),
 (6938,
  'a young man speaks into a microphone as a giant bird head dances behind him.'),
 (7041,
  'a man in a white sports coat sings into the microphone while two men dance behind him'),
 (9170, 'a woman wearing a microphone headset does a dance move'),
 (10099, 'a man sings and dances in front of a microphone'),
 (11473, 'a man sings into a microphone and dances on stage'),
 (19252, 'a woman dances on stage and holds a microphone.'),
 (22561, 'a few boys dance and sing into microphones.'),
 (24349, 'a young female sings and dances with a microphone.'),
 (25134,
  'a woman sings into a microphone with a man and woman on either side smile and bop around some dance movement.'),
 (25443, 'two men with microphone are doing some dance moves'),
 (26677, 'this is a man doing a silly dance holdin

# Rand pattern

In [ ]:
rand_gif_df = train_df.sample(70000)
patterns_to_search = 'random'
train_vidxs, train_corpus = list(rand_gif_df.index.values), list(rand_gif_df[1])

In [ ]:
matchs = [(id, text) for id, text in zip(train_vidxs, train_corpus)]

print(len(matchs))
matchs

70000


[(35513, 'a man is smiling and then begins talking.'),
 (29332, 'a woman in pink is walking down a runway.'),
 (33960, 'a smiling man is walking along and waving'),
 (51079, 'a young man is holding a megaphone in a crowd'),
 (90614, 'a man is laughing then puts his head down'),
 (44551, 'a man falls while trying to jump over a net.'),
 (47420, 'a lady is walking the red carpet posing for pictures'),
 (16559,
  'two young men are in a car, and the one in the front is wearing a seat belt'),
 (8503, 'two young people are seen interacting intimately with one another.'),
 (54994, 'a young man is looking around in confusion.'),
 (83493, 'a boy wearing a beanie is kissing a girl with long brown hair.'),
 (93059, 'a woman sits and poses her arms on the sides of her face'),
 (90955,
  'a young man opens his car door while someone takes pictures of him.'),
 (77891,
  'a young man in the company of a woman takes a shot and throws the glass.'),
 (22443, 'a man is jogging, another man lowers his ce

In [ ]:
id_choice = random.randint(0, len(matchs))
idx = matchs[id_choice][0]

caption = train_df.loc[idx][1]
print(f'caption_original of {idx} gif: {caption}\n')
url =  train_df.loc[idx][0]
Image(url=url)  # external

caption_original of 64102 gif: a man is standing in front of a mirror punching himself in the face and headbutting the mirror



### It's sample of bad gif with several statc frames

In [ ]:
idx = 43250 #matchs[id_choice][0]
caption = train_df.loc[idx][1]
print(f'caption_original of {idx} gif: {caption}\n')
url =  train_df.loc[idx][0]
Image(url=url)  # external

caption_original of 43250 gif: a girl dances from side to side while singing on a microphone in front of two other girls



# Save frames to dir

Becase we take from old GIF dataset, it have short, static and low resolution movis.

We have to select more good movies!

In [ ]:
dir_name = '/content/images'
try:
  os.mkdir(dir_name)
except: pass

In [ ]:
import requests
import numpy as np
import PIL

# what separete
LEN_MOVI = 100
wait_movis = 500
MIN_SIZE = 300
path_gif = '/content/temp.gif' # save gif path
take_min = 15 # q_ty take frame from gif
take_max = LEN_MOVI+1

# for save information to dataframe
select_movis = 0
pil_df = []

for id_matchs in range(len(matchs)):
  bad_movi = 0
  low_movi = 0
  error = 0
  id_movi = matchs[id_matchs][0]
  caption = train_df.loc[id_movi][1]
  url =  train_df.loc[id_movi][0]

  try:
    #download gif
    with open(path_gif, 'wb') as f:
      f.write(requests.get(url).content)

    # open gif
    gif_img = PIL.Image.open(path_gif)

    # take original frames
    frames = [frame.convert('RGB') for frame in PIL.ImageSequence.Iterator(gif_img)]
    width, height = frames[0].size
  except:
    print(f'Non or bad gif')
    error = 1
    frame = []

  if len(frames) < take_min:
    if error == 1: error = 0
    else: print(f'Small gif {id_movi}')

  # select movi not shot than take_min
  else:
    # select movi not low than MIN_SIZE
    if width < MIN_SIZE  or  height < MIN_SIZE:
       print(f'Movi {id_movi} have low H or W')
       low_movi = 1

    if len(frames) > take_max and not low_movi:
      # chack some statick movi
      dif_frames = [(frame - np.array(frames[0])) for frame in frames[1:]]
      dif_frames = np.array(dif_frames)

      for k in range(dif_frames.shape[0]):
          if dif_frames[k].sum() == 0:
            bad_movi+=1
      if not bad_movi:
        frames = frames[:take_max]
        print(f'Cut movi {id_movi}')
    else:
      if bad_movi:
        print(f'Movi {id_movi} have static frames')


    if not bad_movi and not low_movi:
        # save frames and make
        for i in range(len(frames)):
            id_frame = i
            img_path = os.path.join(dir_name, f'{id_movi}_{id_frame}.jpg')
            frames[i].save(img_path)
            pil_df.append([id_movi, f"{width},{height}", id_frame, [width, height], caption, img_path, patterns_to_search])

        select_movis += 1
        print(f'Movi {id_movi} have len = {len(frames)} take all move with W_{width} x H_{height} selected_{select_movis}')

    if select_movis > wait_movis: break

pil_df = pd.DataFrame(pil_df)
pil_df.columns = ['id_movi', "w x h", 'id_frame', 'size_frame', 'caption_movi', 'paths','patterns' ]
pil_df.to_csv('frames_info.csv', index=False)

Movi 35513 have low H or W
Movi 29332 have low H or W
Movi 33960 have low H or W
Movi 51079 have low H or W
Movi 90614 have low H or W
Movi 44551 have low H or W
Movi 47420 have low H or W
Movi 16559 have low H or W
Movi 8503 have low H or W
Movi 54994 have low H or W
Movi 83493 have low H or W
Movi 93059 have low H or W
Movi 90955 have low H or W
Movi 77891 have low H or W
Movi 22443 have low H or W
Movi 98181 have low H or W
Movi 69887 have low H or W
Movi 35429 have low H or W
Movi 13074 have low H or W
Movi 6387 have low H or W
Movi 12456 have low H or W
Movi 80588 have low H or W
Movi 44493 have low H or W
Movi 60426 have low H or W
Movi 85145 have low H or W
Movi 88962 have low H or W
Movi 12995 have low H or W
Movi 47537 have len = 43 take all move with W_636 x H_358 selected_1
Movi 1329 have low H or W
Movi 883 have low H or W
Movi 90168 have low H or W
Movi 95626 have low H or W
Movi 71766 have low H or W
Movi 77514 have low H or W
Movi 49346 have low H or W
Movi 72876 have lo

In [ ]:
pil_df = pd.read_csv('/content/frames_info.csv')
pil_df.sample(10)

id_movi    w x h  id_frame  size_frame  \
2101     6286  500,400        10  [500, 400]   
3579    37229  312,416        35  [312, 416]   
1445     8812  309,320        72  [309, 320]   
1660     7825  647,349        34  [647, 349]   
5445    37782  500,300        26  [500, 300]   
4590    12758  500,305        17  [500, 305]   
1791    31468  320,391         4  [320, 391]   
1839    27788  332,396        24  [332, 396]   
5778    33328  451,300         4  [451, 300]   
1039     2583  350,350        31  [350, 350]   

                                           caption_movi  \
2101  a cat is sneezing multiple times next to his f...   
3579     a guy gives his girlfriend a kiss on the lips.   
1445  two men are rolling a circular material off a ...   
1660  people are holding hands and they clench their...   
5445  a man is holding a microphone while another pe...   
4590  a very small kitten opens its mouth at the sid...   
1791  a guy walks down the street with friends swayi...   
1839  a girl in a tank top is biting the tip of her ...   
5778     a woman is opening the mouth shocked or scared   
1039        a girl looks over her sunglasses and poses.   

                             paths patterns  
2101   /content/images/6286_10.jpg   random  
3579  /content/images/37229_35.jpg   random  
1445   /content/images/8812_72.jpg   random  
1660   /content/images/7825_34.jpg   random  
5445  /content/images/37782_26.jpg   random  
4590  /content/images/12758_17.jpg   random  
1791   /content/images/31468_4.jpg   random  
1839  /content/images/27788_24.jpg   random  
5778   /content/images/33328_4.jpg   random  
1039   /content/images/2583_31.jpg   random

In [ ]:
idx = []
for id, rw in pil_df.loc[:10].iterrows():
  if int(rw["w x h"].split(",")[0]) < MIN_SIZE or int(rw["w x h"].split(",")[1]) < MIN_SIZE:
    idx.append(id)
    print(rw["w x h"])

In [ ]:
pil_df.id_frame.unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

## Play selected frames from dir

In [ ]:
pil_ids = pil_df.id_movi.unique()
pil_ids

array([ 47537,  40666,  46829,  11169,  85989,  14739,  55411,  72371,
        73605,  10765,  64201,  50651,  34369,   3756,   6847,  79894,
         9697,  81500,  14743,  91007,   4692,  59697,  24691,  51628,
         8376,  48022,  99650,  12808,  10901, 102035,  84978,  65498,
        31249,   2583,  60587,  22345,  48610,  56714,  65800,  80689,
        72850,  87526,   6586,  16485,  53208,  94420,   8840,   8812,
         1580,  42851,   5372,  24078,  16380,  52980,   7825,  65721,
        94121,  17266,  33413,  31468,  51185,  27788,  80088,  34979,
         8938,  62948,  31059,  15866,  73519, 100631,   3579,   6286,
        56157,  77053,  23204,  19572,  22287,  52242,   2531,  82236,
        14293,  47496,  20807,  16354,  37347,  55762,  58669,  13016,
        85945,  30580,  58243,  31511,  19852,  18714,  17187,  10325,
        22020,  22351,  29655,  63008,  60790,  25398,  31141,     32,
        52549,  37797,  82521,  50248,   6831,  22862, 101449,  20673,
      

In [ ]:
pil_df[pil_df.id_movi == pil_ids[5]]

id_movi    w x h  id_frame  size_frame  \
159    55411  345,328         0  [345, 328]   
160    55411  345,328         1  [345, 328]   
161    55411  345,328         2  [345, 328]   
162    55411  345,328         3  [345, 328]   
163    55411  345,328         4  [345, 328]   
164    55411  345,328         5  [345, 328]   
165    55411  345,328         6  [345, 328]   
166    55411  345,328         7  [345, 328]   
167    55411  345,328         8  [345, 328]   
168    55411  345,328         9  [345, 328]   
169    55411  345,328        10  [345, 328]   
170    55411  345,328        11  [345, 328]   
171    55411  345,328        12  [345, 328]   
172    55411  345,328        13  [345, 328]   
173    55411  345,328        14  [345, 328]   
174    55411  345,328        15  [345, 328]   
175    55411  345,328        16  [345, 328]   
176    55411  345,328        17  [345, 328]   
177    55411  345,328        18  [345, 328]   
178    55411  345,328        19  [345, 328]   
179    55411  345,328        20  [345, 328]   
180    55411  345,328        21  [345, 328]   
181    55411  345,328        22  [345, 328]   
182    55411  345,328        23  [345, 328]   
183    55411  345,328        24  [345, 328]   
184    55411  345,328        25  [345, 328]   
185    55411  345,328        26  [345, 328]   

                                       caption_movi  \
159  a man with a bloody mouth is shaking his head.   
160  a man with a bloody mouth is shaking his head.   
161  a man with a bloody mouth is shaking his head.   
162  a man with a bloody mouth is shaking his head.   
163  a man with a bloody mouth is shaking his head.   
164  a man with a bloody mouth is shaking his head.   
165  a man with a bloody mouth is shaking his head.   
166  a man with a bloody mouth is shaking his head.   
167  a man with a bloody mouth is shaking his head.   
168  a man with a bloody mouth is shaking his head.   
169  a man with a bloody mouth is shaking his head.   
170  a man with a bloody mouth is shaking his head.   
171  a man with a bloody mouth is shaking his head.   
172  a man with a bloody mouth is shaking his head.   
173  a man with a bloody mouth is shaking his head.   
174  a man with a bloody mouth is shaking his head.   
175  a man with a bloody mouth is shaking his head.   
176  a man with a bloody mouth is shaking his head.   
177  a man with a bloody mouth is shaking his head.   
178  a man with a bloody mouth is shaking his head.   
179  a man with a bloody mouth is shaking his head.   
180  a man with a bloody mouth is shaking his head.   
181  a man with a bloody mouth is shaking his head.   
182  a man with a bloody mouth is shaking his head.   
183  a man with a bloody mouth is shaking his head.   
184  a man with a bloody mouth is shaking his head.   
185  a man with a bloody mouth is shaking his head.   

                            paths patterns  
159   /content/images/55411_0.jpg   random  
160   /content/images/55411_1.jpg   random  
161   /content/images/55411_2.jpg   random  
162   /content/images/55411_3.jpg   random  
163   /content/images/55411_4.jpg   random  
164   /content/images/55411_5.jpg   random  
165   /content/images/55411_6.jpg   random  
166   /content/images/55411_7.jpg   random  
167   /content/images/55411_8.jpg   random  
168   /content/images/55411_9.jpg   random  
169  /content/images/55411_10.jpg   random  
170  /content/images/55411_11.jpg   random  
171  /content/images/55411_12.jpg   random  
172  /content/images/55411_13.jpg   random  
173  /content/images/55411_14.jpg   random  
174  /content/images/55411_15.jpg   random  
175  /content/images/55411_16.jpg   random  
176  /content/images/55411_17.jpg   random  
177  /content/images/55411_18.jpg   random  
178  /content/images/55411_19.jpg   random  
179  /content/images/55411_20.jpg   random  
180  /content/images/55411_21.jpg   random  
181  /content/images/55411_22.jpg   random  
182  /content/images/55411_23.jpg   random  
183  /content/images/5

In [ ]:
import glob
import PIL
import base64
from IPython import display

def make_gif(set_dir_pil,
             out_name = "my_awesome.gif",
             duration = 10,
             loop=0,
             ext = '/*.JPG'):

    if type(set_dir_pil) == str:
       frames = [PIL.Image.open(image) for image in glob.glob(f"{set_dir_pil}{ext}")]

    elif type(set_dir_pil) == list: frames = set_dir_pil

    frame_one = frames[0]
    frame_one.save(out_name, format="GIF", append_images=frames,
               save_all=True, optimize=False, duration=duration, loop=loop)


def show_gif(fname):
    with open(fname, 'rb') as fd:
        b64 = base64.b64encode(fd.read()).decode('ascii')
    return display.HTML(f'<img src="data:image/gif;base64,{b64}" />')

In [ ]:
id_frame = pil_ids[380]
print(f'Selected frames of GIF with id_{id_frame}\n')
pathes = pil_df[pil_df.id_movi == id_frame].paths
pil_images = []
for path in pathes:
  img = PIL.Image.open(path)
  pil_images.append(img)

caption = pil_df[pil_df.id_movi == id_frame].caption_movi.values[0]
print(f'Origional caption:\n{caption}')

Selected frames of GIF with id_22606

Origional caption:
a man with a long beard stares without flinching as he only moves his fingers through his beard.


In [ ]:
fname = "out.gif"
make_gif(pil_images, out_name = fname, duration = 200)
display.display(display.Image(data=fname, format='png'))

Output hidden; open in https://colab.research.google.com to view.

#Optimise memory

In [ ]:
import torch
import os
DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'device is {DEVICE}\n')


torch.cuda.memory_summary(device=DEVICE, abbreviated=False)

device is cuda



'|===========================================================================|\n|                  PyTorch CUDA memory summary, device ID 0                 |\n|---------------------------------------------------------------------------|\n|            CUDA OOMs: 0            |        cudaMalloc retries: 0         |\n|===========================================================================|\n|        Metric         | Cur Usage  | Peak Usage | Tot Alloc  | Tot Freed  |\n|---------------------------------------------------------------------------|\n| Allocated memory      |      0 B   |      0 B   |      0 B   |      0 B   |\n|       from large pool |      0 B   |      0 B   |      0 B   |      0 B   |\n|       from small pool |      0 B   |      0 B   |      0 B   |      0 B   |\n|---------------------------------------------------------------------------|\n| Active memory         |      0 B   |      0 B   |      0 B   |      0 B   |\n|       from large pool |      0 B   |      0 B   |

## flush_memory

In [ ]:
import torch
def flush_memory():
    import gc
    gc.collect()
    torch.cuda.empty_cache()
    torch.cuda.ipc_collect()
    with torch.no_grad():
        for _ in range(3):
          torch.cuda.empty_cache()
          torch.cuda.ipc_collect()


def replace_in_memory(device, to_gpu = [], to_cpu = [], ):
  if len(to_cpu):
    for obj in to_cpu:
      if obj.device != 'cpu': obj.to('cpu')

  flush_memory()

  if len(to_gpu):
    for obj in to_gpu:
      if obj.device != 'gpu': obj.to(device)
  flush_memory()


In [ ]:
flush_memory()
torch.__version__

'2.1.0+cu121'

# Kandinsky encoder prior_T2I

In [ ]:
# https://stackoverflow.com/questions/56081324/why-are-google-colab-shell-commands-not-working
import locale
locale.getpreferredencoding = lambda: "UTF-8"

# лучше тоже в обший install выше, иначе требует строку кода выше
!pip install git+https://github.com/ai-forever/diffusers.git

  Cloning https://github.com/ai-forever/diffusers.git to /tmp/pip-req-build-iuda6j_x
  Running command git clone --filter=blob:none --quiet https://github.com/ai-forever/diffusers.git /tmp/pip-req-build-iuda6j_x
  Resolved https://github.com/ai-forever/diffusers.git to commit 6d7205d1ede5dee997a312823f3e655bd11f9f30
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done


In [ ]:
import sys
from diffusers import KandinskyV22Pipeline, KandinskyV22PriorPipeline
#import torch
import PIL
from torchvision import transforms
from transformers import CLIPVisionModelWithProjection
from diffusers.models import UNet2DConditionModel
import numpy as np


In [ ]:
clip_name = 'kandinsky-community/kandinsky-2-2-prior'
TYPE_TENSORS = torch.float16

image_encoder = CLIPVisionModelWithProjection.from_pretrained(clip_name,
                                                              subfolder='image_encoder'
).to(TYPE_TENSORS).to(DEVICE)

prior_T2I = KandinskyV22PriorPipeline.from_pretrained(clip_name,
                                                      image_encoder=image_encoder,
                                                      torch_dtype=TYPE_TENSORS
)

prior_T2I.to(DEVICE)
flush_memory()

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:88: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Cannot initialize model with low cpu memory usage because `accelerate` was not found in the environment. Defaulting to `low_cpu_mem_usage=False`. It is strongly recommended to install `accelerate` for faster and less memory-intense model loading. You can do so with: 
```
pip install accelerate
```
.


Loading pipeline components...:   0%|          | 0/6 [00:00<?, ?it/s]

### checkpoint prior

We take base Prior

In [ ]:
#from diffusers.models.attention_processor import LoRAAttnProcessor, LoRAAttnAddedKVProcessor
BASE_PATH = '/content/drive/Othercomputers/My_comp/Документы/МФТИ_Наука_о_данных/'
#path_prior = BASE_PATH + '/Kand_22_train_prior_decoder/CHECKPOINTS_1/prior_lora_saves'

## get_embeds

In [ ]:
def get_image_embeds(pil_img, to_square = None, recize = []):

    if to_square:
      width, height = pil_img.size   # Get dimensions
      square_size = min(width, height)

      left = (width - square_size)/2
      top = (height - square_size)/2
      right = (width + square_size)/2
      bottom = (height + square_size)/2

      # Crop the center of the image
      pil_img.crop((left, top, right, bottom))

    if len(recize):
      pil_img = pil_img.resize(recize, PIL.Image.BICUBIC)

    with torch.no_grad():
      inputs = prior_T2I.image_processor(pil_img,
                                        return_tensors="pt")
      outputs = prior_T2I.image_encoder(**inputs.to(DEVICE)).image_embeds
      del inputs
      flush_memory()
    return outputs

def get_text_embeds(text, num_steps_inf = 30, seed = 0):
    return prior_T2I(prompt=text,
                      num_inference_steps=num_steps_inf,
                      num_images_per_prompt=1,
                      generator =  torch.manual_seed(seed)
                      ).image_embeds


In [ ]:
text = "George came home late last night"

prior_tokenizer = prior_T2I.tokenizer

inputs = prior_tokenizer([text],
                          padding="max_length",
                          max_length=prior_tokenizer.model_max_length,
                          truncation=True,
                          return_tensors="pt"
                          )
outputs = prior_T2I.text_encoder(**inputs.to(DEVICE))


In [ ]:
del image_encoder
flush_memory()
torch.cuda.memory_summary(device=DEVICE, abbreviated=False)

'|===========================================================================|\n|                  PyTorch CUDA memory summary, device ID 0                 |\n|---------------------------------------------------------------------------|\n|            CUDA OOMs: 0            |        cudaMalloc retries: 0         |\n|===========================================================================|\n|        Metric         | Cur Usage  | Peak Usage | Tot Alloc  | Tot Freed  |\n|---------------------------------------------------------------------------|\n| Allocated memory      |   6837 MiB |   6837 MiB |   6837 MiB |      0 B   |\n|       from large pool |   6831 MiB |   6831 MiB |   6831 MiB |      0 B   |\n|       from small pool |      5 MiB |      5 MiB |      5 MiB |      0 B   |\n|---------------------------------------------------------------------------|\n| Active memory         |   6837 MiB |   6837 MiB |   6837 MiB |      0 B   |\n|       from large pool |   6831 MiB |   6831 MiB |

# Collect dataset

prepare dataset with embedings images and texts

In [ ]:
# отрисовка прохождения цикла
from tqdm.notebook import tqdm

HEIGHT = 768
WIDTH = 768
pil_ids_movi_unique = pil_df.id_movi.unique()#[:10]
all_data = []

with torch.no_grad(): # prepare data for model and losses with no_grad
    for id_movi in tqdm(pil_ids_movi_unique, unit =" movi "):
        frames_pathes = pil_df[pil_df.id_movi == id_movi].paths
        frames_ids = pil_df[pil_df.id_movi == id_movi].id_frame.values
        # for normal way take before last
        pathes = frames_pathes[:-1]

        image_embeds = []
        ids_frame = []
        for i, path in enumerate(pathes):
            # seperate all start and random other frames
            if not i or ( i and np.random.random()<1) or i == len(pathes)-1:
                pil_image = PIL.Image.open(path)
                image_embeds.append(get_image_embeds(pil_image,
                                            to_square=True,
                                            recize=(HEIGHT, WIDTH)).cpu())
                # take label frames
                ids_frame.append(int(frames_ids[i]))

        if len(ids_frame):
            caption = pil_df[pil_df.id_movi == id_movi].caption_movi.values[0]

            inputs = prior_tokenizer([caption],
                                  padding="max_length",
                                  max_length=prior_tokenizer.model_max_length,
                                  truncation=True,
                                  return_tensors="pt"
                                  ).to(DEVICE)

            dict_movi = dict()
            dict_movi['id_movi'] = id_movi
            dict_movi['img_embeds'] = image_embeds
            dict_movi['last_hidden_state'] = prior_T2I.text_encoder(**inputs).last_hidden_state.cpu()
            dict_movi['text_embed'] = get_text_embeds(caption).cpu()
            dict_movi['ids_frames'] = ids_frame
            del(image_embeds, inputs)
            flush_memory()
            all_data.append(dict_movi)


  0%|          | 0/501 [00:00<?, ? movi /s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

## save tensors data

In [ ]:
path_data = BASE_PATH + f"/Kand_22_Spliter/Train/BothWays_Spliter/data/bothway_embed_data_min_{MIN_SIZE}.pth"
torch.save(all_data, path_data)

In [ ]:
loaded_data = torch.load(path_data)

Sample of data for 1 movi

In [ ]:
loaded_data[120]

{'id_movi': 46063,
 'img_embeds': [tensor([[ 0.8774,  0.8418,  1.0713,  ..., -0.6982, -0.5288,  2.4121]],
         dtype=torch.float16),
  tensor([[ 0.9053,  0.7817,  0.9751,  ..., -0.6367, -0.5332,  2.2539]],
         dtype=torch.float16),
  tensor([[ 0.6733,  1.0732,  1.0918,  ..., -0.7266, -0.4897,  2.6055]],
         dtype=torch.float16),
  tensor([[ 0.8599,  0.7764,  1.1621,  ..., -0.8066, -0.5190,  2.5684]],
         dtype=torch.float16),
  tensor([[ 0.9937,  0.6948,  1.0244,  ..., -0.8750, -0.5684,  2.6680]],
         dtype=torch.float16),
  tensor([[ 1.0166,  0.7295,  0.9556,  ..., -0.7622, -0.6528,  2.6602]],
         dtype=torch.float16),
  tensor([[ 0.8975,  0.7974,  1.0547,  ..., -0.7056, -0.7446,  2.6094]],
         dtype=torch.float16),
  tensor([[ 0.7485,  0.8613,  0.7715,  ..., -0.3606, -0.7339,  2.5664]],
         dtype=torch.float16),
  tensor([[ 0.7759,  0.7026,  1.1484,  ..., -0.6719, -0.8384,  2.6699]],
         dtype=torch.float16),
  tensor([[ 0.8032,  0.7402,  1

In [ ]:
del(loaded_data)
flush_memory()